"""Shipment  Model added

Revision ID: 19e4e5045cd8
Revises: 7af578dd056b
Create Date: 2026-06-13 21:02:07.592187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e4e5045cd8'
down_revision: Union[str, Sequence[str], None] = '7af578dd056b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, foreign_key='orders.order_id'),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipment_method', sa.String(length=50), nullable=True),
    sa.Column('shipment_status', sa.Enum('pending', 'shipped', 'delivered', 'returned'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('tracking_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
