"""Order Model added

Revision ID: 87fd917ce0c6
Revises: 2edf46d21763
Create Date: 2026-06-13 16:19:38.600646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fd917ce0c6'
down_revision: Union[str, Sequence[str], None] = '2edf46d21763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='user.id'),
    sa.Column('shipping_address_id', sa.Integer(), nullable=False, foreign_key='address.id'),
    sa.Column('billing_address_id', sa.Integer(), nullable=False, foreign_key='address.id'),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('credit_card', 'paypal', 'bank_transfer', name='payment_method_enum'), nullable=False),
    sa.Column('pending_status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='order_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
