"""Age is added to employee table

Revision ID: f1f34926c2e2
Revises: a101a4f2e05e
Create Date: 2026-06-09 15:59:54.103398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f34926c2e2'
down_revision: Union[str, Sequence[str], None] = 'a101a4f2e05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'age')
    # ### end Alembic commands ###
