"""Order model updated

Revision ID: 54295d019fc9
Revises: b9e940de9f4c
Create Date: 2026-08-01 09:20:42.844841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54295d019fc9'
down_revision: Union[str, Sequence[str], None] = 'b9e940de9f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orderitems')
    op.add_column('orders', sa.Column('totalBillAmount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('contact', sa.String(length=10), nullable=False))
    op.add_column('orders', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('payment_mode', sa.String(length=10), nullable=False))
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.add_column('orders', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.drop_column('orders', 'payment_mode')
    op.drop_column('orders', 'date')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'contact')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'totalBillAmount')
    op.create_table('orderitems',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('orderitems_ibfk_1')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('orderitems_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orderItems')
    # ### end Alembic commands ###
