"""Readingbook  model added

Revision ID: 3123a0e7abc9
Revises: 3f6afd1dd0f2
Create Date: 2026-06-23 09:21:46.293716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3123a0e7abc9'
down_revision: Union[str, Sequence[str], None] = '3f6afd1dd0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_book')
    # ### end Alembic commands ###
