"""post model  added updated without date

Revision ID: 515f14c35bf1
Revises: 69c03f711ea6
Create Date: 2026-06-22 11:11:45.513137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '515f14c35bf1'
down_revision: Union[str, Sequence[str], None] = '69c03f711ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
