"""user model  added updated without date

Revision ID: 69c03f711ea6
Revises: 1c6961313fe7
Create Date: 2026-06-22 10:28:09.073995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69c03f711ea6'
down_revision: Union[str, Sequence[str], None] = '1c6961313fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
