"""classroom  table added

Revision ID: 80587f6e289e
Revises: b24f99dc043a
Create Date: 2026-06-21 22:44:00.304127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80587f6e289e'
down_revision: Union[str, Sequence[str], None] = 'b24f99dc043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clasroom_name', sa.String(length=100), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('classroom_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student', 'classroom', ['classroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'classroom_id')
    op.drop_table('classroom')
    # ### end Alembic commands ###
