"""orders model added

Revision ID: 57d0f404b258
Revises: 81bb35485abf
Create Date: 2026-07-16 11:27:00.740043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57d0f404b258'
down_revision: Union[str, Sequence[str], None] = '81bb35485abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=70),
               existing_nullable=False)
    op.alter_column('user', 'contact',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'contact',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('orders')
    # ### end Alembic commands ###
